### PR TITLE
Support persistent-2.14

### LINKED ISSUE #1759: `yesod-persistent-1.6.0.7` fails to build with `persistent-2.14.0.0`
`yesod-persistent-1.6.0.7` fails to build with `persistent-2.14.0.0`:

```
$ cabal repl -b yesod-persistent --constraint="persistent==2.14.0.0" -w ghc-9.0.2
Resolving dependencies...
Build profile: -w ghc-9.0.2 -O1
In order, the following will be built (use -v for more details):
 - yesod-persistent-1.6.0.7 (lib) (requires build)
 - fake-package-0 (lib) (first run)
Starting     yesod-persistent-1.6.0.7 (lib)
Building     yesod-persistent-1.6.0.7 (lib)

Failed to build yesod-persistent-1.6.0.7.
Build log (
/home/ryanglscott/.cabal/logs/ghc-9.0.2/yesod-persistent-1.6.0.7-a3bdbcb14a59518d7dd131eecf33a57d2ec29c106c04f7e7aa49ef8edbea502c.log
):
Configuring library for yesod-persistent-1.6.0.7..
Preprocessing library for yesod-persistent-1.6.0.7..
Building library for yesod-persistent-1.6.0.7..
[1 of 2] Compiling Yesod.Persist.Core ( Yesod/Persist/Core.hs, dist/build/Yesod/Persist/Core.o, dist/build/Yesod/Persist/Core.dyn_o )

Yesod/Persist/Core.hs:212:20: error:
    • Could not deduce (Database.Persist.Class.PersistEntity.SafeToInsert
                          val)
        arising from a use of ‘insert’
      from the context: (MonadIO m, PersistUniqueWrite backend,
                         PersistRecordBackend val backend)
        bound by the type signature for:
                   insert400 :: forall (m :: * -> *) backend val.
                                (MonadIO m, PersistUniqueWrite backend,
                                 PersistRecordBackend val backend) =>
                                val -> ReaderT backend m (Key val)
        at Yesod/Persist/Core.hs:(191,1)-(193,40)
      Possible fix:
        add (Database.Persist.Class.PersistEntity.SafeToInsert
               val) to the context of
          the type signature for:
            insert400 :: forall (m :: * -> *) backend val.
                         (MonadIO m, PersistUniqueWrite backend,
                          PersistRecordBackend val backend) =>
                         val -> ReaderT backend m (Key val)
    • In the expression: insert datum
      In a case alternative: Nothing -> insert datum
      In a stmt of a 'do' block:
        case conflict of
          Just unique
            -> badRequest'
                 $ map (unFieldNameHS . fst)
                     $ toList $ persistUniqueToFieldNames unique
          Nothing -> insert datum
    |
212 |         Nothing -> insert datum
    |                    ^^^^^^^^^^^^
cabal: Failed to build yesod-persistent-1.6.0.7 (which is required by
fake-package-0). See the build log above for details.
```

On the other hand, it compiles if I use `persistent-2.13.3.5` instead.

### PR DESCRIPTION
**Pull request by parsonsmatt**
Fixes #1759 

Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddocks for new, public APIs

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Review by snoyberg — APPROVED** [review]
Thanks!

**Comment by parsonsmatt** [comment]
@snoyberg can I ping you for a release and/or to be added to the maintainers on Hackage for `yesod-persistent`? Thanks!

**Comment by snoyberg** [comment]
Sorry, I thought I'd released! I'm not at my main computer right now, and having you on the maintainer list is a good idea anyway. I've added you on Hackage. If you could make a release, that would be great!

**Comment by parsonsmatt** [comment]
You got it 👍🏻 Thanks!
