### ISSUE TITLE
yesod-bin fails to build with ghc-7.10.1

### ISSUE THREAD

**Issue by snakamura** [yesodweb/yesod#965]
I found that yesod-bin failed to build with ghc-7.10.1. Some of them are caused by BBP and easy to be fixed, but some of them are caused by the changes of ghc package and need investigations. For example, I got these errors.

    [ 1 of 10] Compiling GhcBuild         ( GhcBuild.hs, dist/build/yesod/yesod-tmp/GhcBuild.o )

    GhcBuild.hs:90:35:
        Not in scope: ‘Module.packageIdString’
        Perhaps you meant ‘Module.packageKeyString’ (imported from Module)

    GhcBuild.hs:94:21:
        Not in scope: data constructor ‘DF.ExposePackageId’
        Perhaps you meant ‘DF.ExposePackage’ (imported from DynFlags)

I'm not familiar with ghc library and wondering if someone has already started working on this issue before looking into them deeply.

**Comment by snoyberg** [comment]
@luite This is in the part of the code I've never touched. Any chance you could have a look at this?

**Comment by snoyberg** [comment]
@Codas added this support in #966. Can you test out master and confirm that it works for you?

**Comment by swamp-agr** [comment]
I test master on GHC 7.10.1 and confirm. 
Everything is OK.

**Comment by snoyberg** [comment]
Cool, thanks! Releasing to Hackage as 1.4.7

**Comment by snakamura** [comment]
Tested 1.4.7 and worked fine. Thank you!
