### ISSUE TITLE
yesod-bin: failed to build with ghc-9.12.2

### ISSUE THREAD

**Issue by juhp** [yesodweb/yesod#1884]
Stackage Nightly says:

```
       Building executable 'yesod' for yesod-bin-1.6.2.3...                                                    16:40:22 [210/986825]
       [1 of 7] Compiling AddHandler                                                                                                
       [2 of 7] Compiling Devel                                                                                                     
       /home/curators/work/unpack-dir/unpacked/yesod-bin-1.6.2.3-40c86dd966aa938fb36b9ab033c5cc3f018d3a6eb771589961ef2656e0abd135/Ad
dHandler.hs:249:41: error: [GHC-83865]                                                                                              
           • Couldn't match expected type: IO                                                                                                                                    Distribution.Types.GenericPackageDescription.GenericPackageDescription                 
                         with actual type: SymbolicPath Pkg File                                                                    
                                           -> IO                                                                                    
                                                Distribution.Types.GenericPackageDescription.GenericPackageDescription              
           • Probable cause: ‘readGenericPackageDescription’ is applied to too few arguments                                        
             In the second argument of ‘(<$>)’, namely                                                                              
               ‘readGenericPackageDescription normal cabal’                                                                         
             In a stmt of a 'do' block:
               pd <- flattenPackageDescription
                       <$> readGenericPackageDescription normal cabal
             In the expression:
               do pd <- flattenPackageDescription
                          <$> readGenericPackageDescription normal cabal
                  let buildInfo = allBuildInfo pd
                      srcDirs = concatMap hsSourceDirs buildInfo
                  return $ maybe "." getSymbolicPath $ listToMaybe srcDirs
           |
       249 |     pd <- flattenPackageDescription <$> readGenericPackageDescription normal cabal
           |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        
       /home/curators/work/unpack-dir/unpacked/yesod-bin-1.6.2.3-40c86dd966aa938fb36b9ab033c5cc3f018d3a6eb771589961ef2656e0abd135/Ad
dHandler.hs:249:78: error: [GHC-83865]
           • Couldn't match type: [Char]
                            with: Maybe (SymbolicPath CWD (Dir Pkg))
             Expected: Maybe (SymbolicPath CWD (Dir Pkg))
               Actual: FilePath
           • In the second argument of ‘readGenericPackageDescription’, namely
               ‘cabal’
             In the second argument of ‘(<$>)’, namely
               ‘readGenericPackageDescription normal cabal’
             In a stmt of a 'do' block:
               pd <- flattenPackageDescription
                       <$> readGenericPackageDescription normal cabal
           |
       249 |     pd <- flattenPackageDescription <$> readGenericPackageDescription normal cabal
           |                                                                              ^^^^^
```

**Comment by oliverepper** [comment]
New to Yesod. Since the documentation suggests installing yesod-bin what are the alternatives? Is there a way to start a project with cabal and still get some scaffolding for yesod?

**Comment by oliverepper** [comment]
Perfect. Thanks a lot. Got me up & dancing. Enjoying Yesod, so far. The book is nice to read.

**Comment by jezen** [comment]
Awesome. Do shout if you need more guidance.

**Comment by oliverepper** [comment]
I am loving that the book doesn't use the scaffolding, in the first place. This is right down my alley! I've started with the chapter https://www.yesodweb.com/book/yesod-for-haskellers and I am already convinced that I will build at least a POC with Yesod. I also find the experiences you describe in the podcast and on your website very useful.
