### ISSUE TITLE
yesod-websockets-0.2.4 fails to build with websockets-0.9.8.0

### ISSUE THREAD

**Issue by juhp** [yesodweb/yesod#1311]
```
Yesod/WebSockets.hs:59:31: error:
    • Couldn't match type ‘WS.Headers -> WS.AcceptRequest’
                     with ‘WS.AcceptRequest’
      Expected type: WS.RequestHead -> m (Maybe WS.AcceptRequest)
        Actual type: WS.RequestHead
                     -> m (Maybe (WS.Headers -> WS.AcceptRequest))
    • In the second argument of ‘($)’, namely
        ‘const $ return $ Just $ WS.AcceptRequest Nothing’
      In the expression:
        webSocketsWith $ const $ return $ Just $ WS.AcceptRequest Nothing
      In an equation for ‘webSockets’:
          webSockets
            = webSocketsWith $ const $ return $ Just $ WS.AcceptRequest Nothing
```
from the Stackage Nightly build

**Comment by juhp** [comment]
FYI @jaspervdj

**Comment by jaspervdj** [comment]
@juhp Thanks for notifying me.  Looks like I accidentally broke the PVP.  I will restore the old version as `0.9.8.1` and then upload the new version as `0.10.0.0`.

**Comment by jaspervdj** [comment]
@juhp Issue should be fixed with `websockets-0.9.8.2`.

**Comment by snoyberg** [comment]
Thanks Jasper!
